<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <RootNamespace>Wolflog.Protocol</RootNamespace>
    <PackageId>Wolflog.Protocol</PackageId>
    <Description>Messages OTLP (OpenTelemetry Protocol) générés pour Wolflog.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="Protos\**\*.proto" ProtoRoot="Protos" GrpcServices="Server" Access="Public" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" Link="README.md" />
  </ItemGroup>
</Project>
