import { Routes } from '@angular/router';
import { adminGuard, authGuard } from './core/guards';

export const routes: Routes = [
  { path: 'login', loadComponent: () => import('./pages/login').then((m) => m.LoginPage), title: 'Connexion · Wolflog' },
  {
    path: '',
    canActivateChild: [authGuard],
    children: [
      { path: '', loadComponent: () => import('./pages/overview').then((m) => m.OverviewPage), title: "Vue d'ensemble · Wolflog" },
      { path: 'dashboards', loadComponent: () => import('./pages/dashboards').then((m) => m.DashboardsPage), title: 'Tableaux de bord · Wolflog' },
      { path: 'dashboards/new', loadComponent: () => import('./pages/dashboard-form').then((m) => m.DashboardFormPage), title: 'Nouveau tableau de bord · Wolflog' },
      { path: 'dashboards/:id', loadComponent: () => import('./pages/dashboard').then((m) => m.DashboardPage), title: 'Tableau de bord · Wolflog' },
      { path: 'requests', loadComponent: () => import('./pages/requests').then((m) => m.RequestsPage), title: 'Requêtes HTTP · Wolflog' },
      { path: 'logs', loadComponent: () => import('./pages/logs').then((m) => m.LogsPage), title: 'Logs · Wolflog' },
      { path: 'traces', loadComponent: () => import('./pages/traces').then((m) => m.TracesPage), title: 'Traces · Wolflog' },
      { path: 'traces/:id', loadComponent: () => import('./pages/trace-detail').then((m) => m.TraceDetailPage), title: 'Trace · Wolflog' },
      { path: 'errors', loadComponent: () => import('./pages/errors').then((m) => m.ErrorsPage), title: 'Erreurs · Wolflog' },
      { path: 'errors/:fingerprint', loadComponent: () => import('./pages/error-detail').then((m) => m.ErrorDetailPage), title: 'Erreur · Wolflog' },
      { path: 'metrics', loadComponent: () => import('./pages/metrics').then((m) => m.MetricsPage), title: 'Métriques · Wolflog' },
      { path: 'map', loadComponent: () => import('./pages/service-map').then((m) => m.ServiceMapPage), title: 'Carte des services · Wolflog' },
      { path: 'profiles', loadComponent: () => import('./pages/profiles').then((m) => m.ProfilesPage), title: 'Profils · Wolflog' },
      { path: 'alerts/channels/new', canActivate: [adminGuard], loadComponent: () => import('./pages/channel-form').then((m) => m.ChannelFormPage), title: 'Nouveau canal · Wolflog' },
      { path: 'alerts/channels/:id', canActivate: [adminGuard], loadComponent: () => import('./pages/channel-form').then((m) => m.ChannelFormPage), title: 'Canal · Wolflog' },
      { path: 'alerts/new', loadComponent: () => import('./pages/alert-form').then((m) => m.AlertFormPage), title: 'Nouvelle alerte · Wolflog' },
      { path: 'alerts/:id', loadComponent: () => import('./pages/alert-form').then((m) => m.AlertFormPage), title: 'Alerte · Wolflog' },
      { path: 'alerts', loadComponent: () => import('./pages/alerts').then((m) => m.AlertsPage), title: 'Alertes · Wolflog' },
      { path: 'uptime/new', loadComponent: () => import('./pages/probe-form').then((m) => m.ProbeFormPage), title: 'Nouvelle sonde · Wolflog' },
      { path: 'uptime/:id/edit', loadComponent: () => import('./pages/probe-form').then((m) => m.ProbeFormPage), title: 'Sonde · Wolflog' },
      { path: 'uptime', loadComponent: () => import('./pages/uptime').then((m) => m.UptimePage), title: 'Disponibilité · Wolflog' },
      { path: 'slos/new', loadComponent: () => import('./pages/slo-form').then((m) => m.SloFormPage), title: 'Nouvel objectif · Wolflog' },
      { path: 'slos/:id/edit', loadComponent: () => import('./pages/slo-form').then((m) => m.SloFormPage), title: 'Objectif · Wolflog' },
      { path: 'slos', loadComponent: () => import('./pages/slos').then((m) => m.SlosPage), title: 'Objectifs · Wolflog' },
      { path: 'slos/:id', loadComponent: () => import('./pages/slos').then((m) => m.SlosPage), title: 'Objectif · Wolflog' },
      { path: 'account', loadComponent: () => import('./pages/account').then((m) => m.AccountPage), title: 'Mon compte · Wolflog' },
      { path: 'admin/users/new', canActivate: [adminGuard], loadComponent: () => import('./pages/user-form').then((m) => m.UserFormPage), title: 'Ajouter un utilisateur · Wolflog' },
      { path: 'admin/keys/new', canActivate: [adminGuard], loadComponent: () => import('./pages/key-form').then((m) => m.KeyFormPage), title: 'Connecter une application · Wolflog' },
      { path: 'admin/sources/new', canActivate: [adminGuard], loadComponent: () => import('./pages/source-form').then((m) => m.SourceFormPage), title: 'Ajouter une source · Wolflog' },
      { path: 'admin/sources/:id', canActivate: [adminGuard], loadComponent: () => import('./pages/source-form').then((m) => m.SourceFormPage), title: 'Source · Wolflog' },
      { path: 'admin/users', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-users').then((m) => m.AdminUsersPage), title: 'Utilisateurs · Wolflog' },
      { path: 'admin/keys', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-keys').then((m) => m.AdminKeysPage), title: 'Clés API · Wolflog' },
      { path: 'admin/sources', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-sources').then((m) => m.AdminSourcesPage), title: 'Sources · Wolflog' },
      { path: 'system', canActivate: [adminGuard], loadComponent: () => import('./pages/system').then((m) => m.SystemPage), title: 'Système · Wolflog' },
    ],
  },
  { path: '**', redirectTo: '' },
];
