import { Routes } from '@angular/router';
import { adminGuard, authGuard, sectionGuard } from './core/guards';

export const routes: Routes = [
  { path: 'login', loadComponent: () => import('./pages/login').then((m) => m.LoginPage), title: 'Connexion · Wolflog' },
  {
    path: '',
    // data.section : partie de Wolflog (profil d'accès, core/access.ts) ; hors du profil, retour à sa page d'accueil.
    canActivateChild: [authGuard, sectionGuard],
    children: [
      { path: '', data: { section: 'overview' }, loadComponent: () => import('./pages/overview').then((m) => m.OverviewPage), title: "Vue d'ensemble · Wolflog" },
      { path: 'dashboards', data: { section: 'dashboards' }, loadComponent: () => import('./pages/dashboards').then((m) => m.DashboardsPage), title: 'Tableaux de bord · Wolflog' },
      { path: 'dashboards/new', data: { section: 'dashboards' }, loadComponent: () => import('./pages/dashboard-form').then((m) => m.DashboardFormPage), title: 'Nouveau tableau de bord · Wolflog' },
      { path: 'dashboards/:id', data: { section: 'dashboards' }, loadComponent: () => import('./pages/dashboard').then((m) => m.DashboardPage), title: 'Tableau de bord · Wolflog' },
      { path: 'requests', data: { section: 'requests' }, loadComponent: () => import('./pages/requests').then((m) => m.RequestsPage), title: 'Requêtes HTTP · Wolflog' },
      { path: 'logs', data: { section: 'logs' }, loadComponent: () => import('./pages/logs').then((m) => m.LogsPage), title: 'Logs · Wolflog' },
      { path: 'traces', data: { section: 'traces' }, loadComponent: () => import('./pages/traces').then((m) => m.TracesPage), title: 'Traces · Wolflog' },
      { path: 'traces/:id', data: { section: ['traces', 'requests'] }, loadComponent: () => import('./pages/trace-detail').then((m) => m.TraceDetailPage), title: 'Trace · Wolflog' },
      { path: 'errors', data: { section: 'errors' }, loadComponent: () => import('./pages/errors').then((m) => m.ErrorsPage), title: 'Erreurs · Wolflog' },
      { path: 'errors/:fingerprint', data: { section: 'errors' }, loadComponent: () => import('./pages/error-detail').then((m) => m.ErrorDetailPage), title: 'Erreur · Wolflog' },
      { path: 'metrics', data: { section: 'metrics' }, loadComponent: () => import('./pages/metrics').then((m) => m.MetricsPage), title: 'Métriques · Wolflog' },
      { path: 'map', data: { section: 'map' }, loadComponent: () => import('./pages/service-map').then((m) => m.ServiceMapPage), title: 'Carte des services · Wolflog' },
      { path: 'audience', data: { section: 'audience' }, loadComponent: () => import('./pages/audience').then((m) => m.AudiencePage), title: 'Audience · Wolflog' },
      { path: 'clickmaps', data: { section: 'clickmaps' }, loadComponent: () => import('./pages/clickmaps').then((m) => m.ClickmapsPage), title: 'Clics et défilement · Wolflog' },
      { path: 'profiles', data: { section: 'profiles' }, loadComponent: () => import('./pages/profiles').then((m) => m.ProfilesPage), title: 'Profils · Wolflog' },
      { path: 'alerts/channels/new', data: { section: 'alerts' }, canActivate: [adminGuard], loadComponent: () => import('./pages/channel-form').then((m) => m.ChannelFormPage), title: 'Nouveau canal · Wolflog' },
      { path: 'alerts/channels/:id', data: { section: 'alerts' }, canActivate: [adminGuard], loadComponent: () => import('./pages/channel-form').then((m) => m.ChannelFormPage), title: 'Canal · Wolflog' },
      { path: 'alerts/new', data: { section: 'alerts' }, loadComponent: () => import('./pages/alert-form').then((m) => m.AlertFormPage), title: 'Nouvelle alerte · Wolflog' },
      { path: 'alerts/:id', data: { section: 'alerts' }, loadComponent: () => import('./pages/alert-form').then((m) => m.AlertFormPage), title: 'Alerte · Wolflog' },
      { path: 'alerts', data: { section: 'alerts' }, loadComponent: () => import('./pages/alerts').then((m) => m.AlertsPage), title: 'Alertes · Wolflog' },
      { path: 'uptime/new', data: { section: 'uptime' }, loadComponent: () => import('./pages/probe-form').then((m) => m.ProbeFormPage), title: 'Nouvelle sonde · Wolflog' },
      { path: 'uptime/:id/edit', data: { section: 'uptime' }, loadComponent: () => import('./pages/probe-form').then((m) => m.ProbeFormPage), title: 'Sonde · Wolflog' },
      { path: 'uptime', data: { section: 'uptime' }, loadComponent: () => import('./pages/uptime').then((m) => m.UptimePage), title: 'Disponibilité · Wolflog' },
      { path: 'slos/new', data: { section: 'slos' }, loadComponent: () => import('./pages/slo-form').then((m) => m.SloFormPage), title: 'Nouvel objectif · Wolflog' },
      { path: 'slos/:id/edit', data: { section: 'slos' }, loadComponent: () => import('./pages/slo-form').then((m) => m.SloFormPage), title: 'Objectif · Wolflog' },
      { path: 'slos', data: { section: 'slos' }, loadComponent: () => import('./pages/slos').then((m) => m.SlosPage), title: 'Objectifs · Wolflog' },
      { path: 'slos/:id', data: { section: 'slos' }, loadComponent: () => import('./pages/slos').then((m) => m.SlosPage), title: 'Objectif · Wolflog' },
      { path: 'account', loadComponent: () => import('./pages/account').then((m) => m.AccountPage), title: 'Mon compte · Wolflog' },
      { path: 'admin/users/new', canActivate: [adminGuard], loadComponent: () => import('./pages/user-form').then((m) => m.UserFormPage), title: 'Ajouter un utilisateur · Wolflog' },
      { path: 'admin/keys/new', canActivate: [adminGuard], loadComponent: () => import('./pages/key-form').then((m) => m.KeyFormPage), title: 'Connecter une application · Wolflog' },
      { path: 'admin/sources/new', canActivate: [adminGuard], loadComponent: () => import('./pages/source-form').then((m) => m.SourceFormPage), title: 'Ajouter une source · Wolflog' },
      { path: 'admin/sources/:id', canActivate: [adminGuard], loadComponent: () => import('./pages/source-form').then((m) => m.SourceFormPage), title: 'Source · Wolflog' },
      { path: 'admin/users', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-users').then((m) => m.AdminUsersPage), title: 'Utilisateurs · Wolflog' },
      { path: 'admin/access', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-access').then((m) => m.AdminAccessPage), title: "Profils d'accès · Wolflog" },
      { path: 'admin/keys', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-keys').then((m) => m.AdminKeysPage), title: 'Clés API · Wolflog' },
      { path: 'admin/sso', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-sso').then((m) => m.AdminSsoPage), title: 'Connexion SSO · Wolflog' },
      { path: 'admin/sources', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-sources').then((m) => m.AdminSourcesPage), title: 'Sources · Wolflog' },
      { path: 'admin/branding', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-branding').then((m) => m.AdminBrandingPage), title: 'Personnalisation · Wolflog' },
      { path: 'admin/environments', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-environments').then((m) => m.AdminEnvironmentsPage), title: 'Environnements · Wolflog' },
      { path: 'system', canActivate: [adminGuard], loadComponent: () => import('./pages/system').then((m) => m.SystemPage), title: 'Système · Wolflog' },
    ],
  },
  { path: '**', redirectTo: '' },
];
